### ISSUE TITLE
Bids not saving

### ISSUE THREAD

**Issue by 0x4849a** [CMPUT301W16T15/Shareo#10]
Bidding kinda works(you can see the number of bids increasing if you re-click the same item from the search after doing a bid) but if you switch tabs away from search or re-do the search and click on the item again, the number of bids for Thing (as per thing.getBids()) resets to 0 after. Not sure why. Pretty fail.

**Comment by 0x4849a** [comment]
It's also worth noting that a number of bids fail to build.. You can bid on all of the games here : https://github.com/CMPUT301W16T15/Shareo/blob/master/testcases

But if you make a new game without a picture for example, the bid wont build (NullIDException).

**Comment by Bradshawz** [comment]
execute.getSourceAsObjectList(Thing.class) in ShareoData sometimes doesn't set the jestID... and i have no idea why. Looking into.

**Comment by Bradshawz** [comment]
@JestID annotation doesn't seem to work in superclasses.

**Comment by 0x4849a** [comment]
Nice job.. that fixes the second issue. Now all games seem to have bids built successfully.But I think the bids still arent saving because if u redo the search or switch tabs after bidding on an item, the thing.getBids() resets to size 0 again. So I am not sure what the issue is with that.

**Comment by Bradshawz** [comment]
The method for adding a bid to a game was not adding the bid ID. That is fixed now. However, now we have to deal with the fact it will crash every time there is a bid on the game because getBids is an asynchonous call. I would frontload getting bid information when we grab the game from search, but we pass it around using serialization which would destroy the bid information. Easiest method is to create an async task in bids fragment to load the info. Not very clean, but the easiest.
