### ISSUE TITLE
Deleting a Thing sometimes causes User to be deleted

### ISSUE THREAD

**Issue by 0x4849a** [CMPUT301W16T15/Shareo#17]
I think I tested this with making a new account, then making one thing and deleting it.
You can't make a new user with the same name, but you can't login with that user either.
I've noticed this bug appearing with deleting bids as well(perhaps only if you delete the same bid twice?).. 

Note that the deletion uses : mThing.new Deleter().delete(); as that's the only way to delete something inside of thing.

**Comment by Bradshawz** [comment]
It probably isn't deleting the user, but right now any error while loading a user will tell you the user doesn't exist (probably shouldn't, but really there shouldn't be any errors while loading user information). I image somethings going on where a user still holds onto an id of a deleted game. Could either retroactively fix errors(game doesn't exist, ignore and delete id and move on) but ideally should find the root cause.

**Comment by Bradshawz** [comment]
Owner wasn't updating itself online. Fixed.
