### ISSUE TITLE
Back Button on Home, Profile, Bids, Search fragments

### ISSUE THREAD

**Issue by 0x4849a** [CMPUT301W16T15/Shareo#3]
I put in a back button for AddEditGameFragment, but the back button for those other fragments is more complex because you could potentially access those four fragments from any combination of other fragments.

Currently none of these fragments have a back button function.

**Comment by ahoskins** [comment]
in 9b63a84339e7bdc9efd0f55f43ff148efb0b4b1e, I made the add game activity a dialogfragment instead.  This makes nav less confusing.  

The dialogFragment prevents the user from navigating to any of the other taps on top.  I think it will make our lives easier in the long run to have AddEditGameFragment as a dialog instead of a basic fragment :+1:

**Comment by 0x4849a** [comment]
Yeah, I dont think we need a back button in the rest of the tab layout anyways. It probably wasn't designed to have one since from what I can see, you can basically swipe the screen left and right.

Fair enough sir :p
